### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by Ryanizleee** [nahtedetihw/CenteredLabels#3]
I'm getting this error when I'm trying to install CenteredLabels in Cydia or Installer.

My device is a iPhone 12 Pro Max on iOS14.3RC running unc0ver 6.1.1, and I'm pretty sure on the depiction it says that its compatible.

Edit : All packages from your repo is giving me the same error. Packages from other repos installs fine.

Edit2 : Scratch all of that, don't know what I did but the packages installs fine now. Magical.

![9CE164EF-3F85-4D82-B627-068724FE5F3E](https://user-images.githubusercontent.com/21989404/112773065-0ed7ff80-9067-11eb-83d0-85ce3f0dd2db.png)

**Comment by nahtedetihw** [comment]
I think I just updated the repo for something else and you must have been trying to install at the same time. Glad it's all sorted though!

**Comment by Ryanizleee** [comment]
Ahh, installation at the wrong time.
What timing!
And thx for clarifying.
